#!/usr/bin/env python3
"""
Add 16 new images to guides/nephrology-atlas.html.
Inserts new items into existing sections and adds new sections where needed.
Updates stat pills and tab counts.
"""
from pathlib import Path

GUIDE = Path('guides/nephrology-atlas.html')
html = GUIDE.read_text(encoding='utf-8')

# ── NEW ANATOMY ITEMS for section 1 "Gross & spatial anatomy" ────────────────
NEW_ANAT_S1 = """,
          { id:'a11', num:'11', title:'Urinary System — Full Anatomy & Physiology Overview',   webp:'../images/urinary-system-anatomy-physiology-overview-hybrid.webp',  png:'../images/urinary-system-anatomy-physiology-overview-hybrid.png',  alt:'Urinary system full anatomy and physiology overview — kidneys, ureters, bladder, urethra hybrid diagram', accent:'teal',  render:'Hybrid', desc:'Comprehensive hybrid diagram of the complete urinary system: bilateral kidneys (T12–L3), ureters (25–30 cm) with three physiologic narrowings, bladder (400–600 mL capacity), and urethra. Overlaid physiology: GFR 100–125 mL/min, daily filtrate 180 L, final urine 1–2 L/day. Kidney microanatomy inset with cortex (glomeruli + PCT/DCT) and medulla (loops of Henle + collecting ducts). Innervation summary: sympathetic T10–L1, parasympathetic S2–S4 (detrusor). Essential orientation plate before studying individual components.', steps:[], tags:[{cls:'ct-teal',text:'GFR Reference'},{cls:'ct-amber',text:'Three Narrowings'},{cls:'ct-navy',text:'T12–L3 Position'},{cls:'ct-green',text:'1–2 L/day Urine'}] },
          { id:'a12', num:'12', title:'Urinary System — CT Coronal Reconstruction (Labeled)',  webp:'../images/urinary-system-ct-coronal-labeled.webp',                   png:'../images/urinary-system-ct-coronal-labeled.png',                   alt:'Urinary system CT coronal reconstruction with radiologic labels — kidneys, ureters, bladder, adrenal glands',         accent:'amber', render:'Hybrid', desc:'Coronal CT urogram-style reconstruction with complete radiologic labeling: renal parenchyma (cortex vs medulla HU values), collecting system calyces and pelvis, UPJ (ureteropelvic junction), proximal/mid/distal ureter, UVJ (ureterovesical junction), bladder dome and trigone. Adrenal glands labeled superiorly. Right kidney sits 1–2 cm lower than left (hepatic displacement). Left renal vein crosses anterior to aorta. Psoas major silhouette for spatial orientation. Useful for interpreting CT KUB reports.', steps:[], tags:[{cls:'ct-amber',text:'CT Urogram Style'},{cls:'ct-teal',text:'UPJ / UVJ'},{cls:'ct-navy',text:'Radiologic Labels'},{cls:'ct-red',text:'Right Kidney Lower'}] },
          { id:'a13', num:'13', title:'Urinary Tract — Male vs Female Comparative Anatomy',    webp:'../images/urinary-tract-male-female-normal-anatomy-hybrid.webp',      png:'../images/urinary-tract-male-female-normal-anatomy-hybrid.png',      alt:'Urinary tract male vs female comparative anatomy — urethral length, bladder, prostate hybrid diagram',                accent:'red',   render:'Hybrid', desc:'Side-by-side hybrid comparison of male and female lower urinary tract anatomy. Male: urethra 18–22 cm (prostatic 3 cm + membranous 1–2 cm + spongy 15 cm), prostate at bladder neck, external urethral sphincter at membranous urethra. Female: urethra 3–4 cm, external meatus anterior to vaginal introitus — anatomic basis for 50× higher UTI incidence than males. Trigone, detrusor, and urothelium common to both. Clinically critical for understanding catheterization difficulty, BPH, post-void residual, and UTI pathogenesis.', steps:[], tags:[{cls:'ct-teal',text:'Urethral Length'},{cls:'ct-red',text:'UTI Risk Anatomy'},{cls:'ct-amber',text:'Prostate Relations'},{cls:'ct-navy',text:'Detrusor / Trigone'}] },
          { id:'a14', num:'14', title:'Renal Lymphatics, Innervation & Pain Referral Patterns', webp:'../images/renal-lymphatics-innervation-pain-referral-hybrid.webp',    png:'../images/renal-lymphatics-innervation-pain-referral-hybrid.png',    alt:'Renal lymphatics innervation and pain referral — para-aortic nodes, T10-L1 sympathetic, flank and ureteric colic patterns', accent:'navy',  render:'Hybrid', desc:'Three-panel hybrid: (1) Lymphatic drainage — hilar channels drain to para-aortic nodes (L1–L2 level) → cisterna chyli → thoracic duct. Lymph node mapping guides oncologic staging for RCC and upper tract urothelial carcinoma. (2) Autonomic innervation — sympathetic fibers (T10–L1) via lesser and least splanchnic nerves form the renal plexus around the renal artery; target of renal denervation catheter for resistant hypertension. (3) Pain referral map — renal capsule stretch: CVA flank pain; ureteral colic: T11–L2 → inguinal/scrotal/labial radiation; bladder: suprapubic; urethra: penile/urethral burning.', steps:[], tags:[{cls:'ct-teal',text:'Para-aortic Nodes'},{cls:'ct-amber',text:'T10–L1 Innervation'},{cls:'ct-red',text:'Ureteric Colic Map'},{cls:'ct-navy',text:'Renal Denervation'}] }"""

# Anchor: end of a10 entry in anatomy section 1
A10_END = """          { id:'a10', num:'10', title:'Collecting System, Ureters & UVJ — Hybrid Panel',    webp:'../images/kidney-collecting-system-hybrid-v2.webp',   png:'../images/kidney-collecting-system-hybrid-v2.png',   alt:'Kidney collecting system — hybrid diagram of calyces, renal pelvis and ureteropelvic junction',        accent:'red',    render:'Hybrid', desc:'Hybrid diagram of the complete collecting system: minor calyces receive papillary urine → merge into 2–3 major calyces → renal pelvis → ureter. Three anatomic narrowing points prone to stone impaction: ureteropelvic junction (UPJ), pelvic brim crossing of the iliac vessels, and ureterovesical junction (UVJ). The UVJ uses a passive anti-reflux valve mechanism (oblique intramural passage through bladder wall).', steps:[], tags:[] },"""

html = html.replace(A10_END, A10_END + NEW_ANAT_S1 + ",", 1)

# ── NEW ANATOMY ITEM for section 2 "Nephron & filtration barrier" ─────────────
NEW_ANAT_S2 = """,
          { id:'a15', num:'15', title:'Juxtaglomerular Apparatus — RAAS Trigger & Renin Release', webp:'../images/juxtaglomerular-apparatus-detailed-hybrid.webp', png:'../images/juxtaglomerular-apparatus-detailed-hybrid.png', alt:'Juxtaglomerular apparatus detailed hybrid — granular cells, macula densa, Lacis cells and RAAS axis', accent:'green', render:'Hybrid', desc:'Detailed hybrid cross-section of the JGA at the vascular pole of the glomerulus: (1) Granular (juxtaglomerular) cells — modified smooth muscle in the afferent arteriole wall, store and release renin in response to decreased stretch (↓BP), β₁-adrenergic stimulation, or low tubular NaCl signal from macula densa. (2) Macula densa — specialized NaCl-sensing cells at the end of the thick ascending limb; low luminal NaCl → prostaglandins and NO → stimulate renin release. (3) Lacis (extraglomerular mesangial) cells — signal transmission. Clinical: ACE inhibitors and ARBs block downstream Ang II, causing efferent dilation and risk of ΔCr rise in bilateral RAS or solitary kidney.', steps:['↓Renal perfusion pressure → stretch-sensitive granular cells release renin','Macula densa senses ↓NaCl in TAL → PGE₂/NO → granular cell renin release','Renin cleaves angiotensinogen → Ang I; ACE (lung) → Ang II','Ang II: efferent constriction + aldosterone + ADH + thirst → restore GFR and BP'], tags:[{cls:'ct-green',text:'Renin Release'},{cls:'ct-amber',text:'Macula Densa NaCl'},{cls:'ct-navy',text:'ACEi/ARB Target'},{cls:'ct-teal',text:'RAAS Axis'}] }"""

A8_END = """          { id:'a8',  num:'08', title:'Podocyte & Slit Diaphragm — EM-Style 3D Render',     webp:'../images/glomerular-barrier-3d.webp',               png:'../images/glomerular-barrier-3d.png',                alt:'Glomerular filtration barrier — 3D cross-section of podocyte foot processes and GBM',                   accent:'navy',   render:'3D',     desc:'Electron-microscopy-style 3D render of podocyte foot processes interdigitating over the GBM, showing the complex slit diaphragm architecture. Nephrin forms a zipper-like structure across the slit. Podocytes are terminally differentiated — they cannot regenerate after injury. Foot process effacement (flattening) is the ultrastructural hallmark of minimal change disease and early diabetic nephropathy.', steps:[], tags:[] },"""

html = html.replace(A8_END, A8_END + NEW_ANAT_S2 + ",", 1)

# ── NEW ANATOMY SECTIONS ──────────────────────────────────────────────────────
NEW_ANAT_SECTIONS = """      },
      {
        title: 'Urogenital anatomy', badge: 'Male & Female', badgeClass: 'badge-red',
        items: [
          { id:'a16', num:'16', title:'Male Urogenital System — 3D Anatomy & Nephrology Correlates', webp:'../images/male-reproductive-system-anatomy-3d.webp',  png:'../images/male-reproductive-system-anatomy-3d.png',  alt:'Male urogenital system 3D anatomy — kidneys ureters bladder prostate seminal vesicles nephrology correlates', accent:'red', render:'3D', desc:'3D rendering of the complete male urogenital system: kidneys, ureters, bladder, prostate (transition zone / peripheral zone), seminal vesicles, vas deferens, urethra (prostatic / membranous / spongy segments), testes, and epididymis. Nephrology highlights: (1) BPH of transition zone → bladder outlet obstruction → bilateral hydroureteronephrosis → CKD (obstructive nephropathy — potentially reversible); (2) Post-renal AKI from acute urinary retention — bladder scan; (3) Testosterone effects on CKD: erythropoiesis stimulation, muscle anabolism; (4) Wolffian (mesonephric) duct embryological derivatives labeled. Essential context for TURBT (P17) and RARP (P18).', steps:[], tags:[{cls:'ct-red',text:'BPH → Obstructive CKD'},{cls:'ct-amber',text:'Wolffian Derivatives'},{cls:'ct-navy',text:'Post-renal AKI'},{cls:'ct-teal',text:'Testosterone & CKD'}] },
          { id:'a17', num:'17', title:'Female Urogenital System — 3D Anatomy & Nephrology Correlates', webp:'../images/female-reproductive-system-anatomy-3d.webp', png:'../images/female-reproductive-system-anatomy-3d.png', alt:'Female urogenital system 3D anatomy — kidneys ureters bladder uterus ovaries urethral length nephrology correlates', accent:'red', render:'3D', desc:'3D rendering of female urogenital anatomy: kidneys, ureters, bladder (with ureteral orifices and trigone), urethra (3–4 cm — 50× shorter than male), uterus, ovaries, fallopian tubes, vagina. Nephrology-relevant highlights: (1) Short urethra + proximity to vagina/anus → periurethral colonization and ascending UTI (ascending infection p/w cystitis → pyelonephritis); (2) Ureteral compression in pregnancy (especially right side by uterus and ovarian vein) → physiologic hydronephrosis; (3) Uteroplacental hypoperfusion → preeclampsia pathway (antiangiogenic factors sFlt-1/PIGF); (4) Lupus nephritis (LN) predominance in women of reproductive age; (5) Müllerian duct embryological derivatives labeled.', steps:[], tags:[{cls:'ct-red',text:'UTI Susceptibility'},{cls:'ct-amber',text:'Pregnancy Hydronephrosis'},{cls:'ct-teal',text:'Preeclampsia Pathway'},{cls:'ct-navy',text:'Lupus Nephritis Risk'}] },
        ]
      },
      {
        title: 'Renal physiology', badge: 'Urine formation & acidification', badgeClass: 'badge-green',
        items: [
          { id:'a18', num:'18', title:'Urine Formation — Filtration, Reabsorption & Secretion', webp:'../images/urine-formation-visual-aid-hybrid.webp',      png:'../images/urine-formation-visual-aid-hybrid.png',      alt:'Urine formation visual aid — glomerular filtration reabsorption secretion and final urine composition hybrid diagram', accent:'green', render:'Hybrid', desc:'Three-process visual aid for urine formation: (1) Glomerular filtration — 180 L/day ultrafiltrate at GFR 125 mL/min driven by Starling forces (Pgc 60 mmHg favoring filtration vs πgc 28 + Pbs 18 mmHg opposing); filtration fraction ~20%. (2) Tubular reabsorption — 99% of filtrate reclaimed: PCT (67% Na, water, all glucose, amino acids, HCO₃), thin DL (water only), TAL (25% Na, no water — diluting segment), DCT (NCC, 5% Na), CD (ENaC + aquaporins regulated by ADH). (3) Tubular secretion — H⁺, K⁺, NH₄⁺, organic anions (creatinine, drugs). Final urine: 1–2 L/day, osmolality 50–1200 mOsm/kg.', steps:['GFR 125 mL/min → 180 L/day filtered; only 1–2 L excreted as urine','PCT: 67% Na/water reabsorbed; 100% glucose; all amino acids','TAL (NKCC2): 25% NaCl reabsorbed, water impermeable — creates diluting segment','CD: ADH-regulated water (AQP2) + aldosterone-regulated Na (ENaC)'], tags:[{cls:'ct-teal',text:'GFR 125 mL/min'},{cls:'ct-amber',text:'99% Reabsorption'},{cls:'ct-green',text:'ADH / AQP2'},{cls:'ct-navy',text:'Aldosterone ENaC'}] },
          { id:'a19', num:'19', title:'Urine Acidification — Proximal & Distal Mechanisms',    webp:'../images/urine-acidification-visual-aid-hybrid.webp',  png:'../images/urine-acidification-visual-aid-hybrid.png',  alt:'Urine acidification visual aid — PCT bicarbonate reclamation and collecting duct net acid secretion hybrid diagram', accent:'green', render:'Hybrid', desc:'Two-panel acid–base physiology: (1) PCT — bicarbonate reclamation (85–90% of filtered HCO₃): luminal H⁺ secreted by NHE3 (Na/H exchanger) + H-ATPase; H⁺ + filtered HCO₃ → H₂CO₃ → CO₂ + H₂O (catalyzed by luminal CA IV); CO₂ enters cell → CA II regenerates HCO₃ → exits basolaterally via NBC1. Net effect: HCO₃ "reclaimed," not new acid secreted. (2) Collecting duct — net acid secretion: type A intercalated cells secrete H⁺ via H-ATPase and H/K-ATPase; H⁺ buffered by NH₃ (→NH₄⁺, titratable acid via phosphate); type B intercalated cells secrete HCO₃ during alkalosis. RTA types: Type I (distal — H-ATPase failure, urine pH >5.5, hypokalemia); Type II (proximal — HCO₃ threshold ↓, hypokalemia); Type IV (aldosterone deficiency/resistance, hyperkalemia).', steps:['PCT: NHE3 + H-ATPase secrete H⁺; CA IV/II regenerate HCO₃; 85% HCO₃ reclaimed','Thick ascending limb and DCT: fine-tune HCO₃ reabsorption','Collecting duct type A cells: H-ATPase net acid secretion; NH₄⁺ + titratable acid buffers','Type B cells secrete HCO₃ in alkalosis; aldosterone governs K/H exchange'], tags:[{cls:'ct-green',text:'Carbonic Anhydrase'},{cls:'ct-amber',text:'NHE3 / H-ATPase'},{cls:'ct-red',text:'RTA Types I-II-IV'},{cls:'ct-navy',text:'Ammoniagenesis'}] },
        ]"""

# Replace the close of the second anatomy section (after a8+new JGA item)
OLD_ANAT_S2_END = """        ]
      }
    ]
  },
  conditions:"""

html = html.replace(OLD_ANAT_S2_END, NEW_ANAT_SECTIONS + """
      }
    ]
  },
  conditions:""", 1)

# ── NEW CONDITION ITEMS ───────────────────────────────────────────────────────
NEW_COND_S1 = """,
          { id:'c13', num:'13', title:'Vesicoureteral Reflux — VUR Grading I–V & Management',  webp:'../images/vesicoureteral-reflux-grading-hybrid.webp',          png:'../images/vesicoureteral-reflux-grading-hybrid.png',          alt:'Vesicoureteral reflux grading I-V — VUR grading hybrid diagram with management algorithm and reflux nephropathy', accent:'teal',  render:'Hybrid', desc:'International Reflux Study grading system illustrated: Grade I — reflux into non-dilated ureter only; Grade II — fills renal pelvis, no dilation, normal fornices; Grade III — mild ureteral and pelvic dilation, blunted fornices; Grade IV — moderate dilation and tortuosity, blunted fornices; Grade V — gross dilation and tortuosity, absent papillary impressions. Reflux nephropathy: repeated infected urine reflux → intrarenal reflux at compound papillae → renal scarring → focal cortical atrophy → CKD. Management: Grade I–III — antibiotic prophylaxis ± watchful waiting (most resolve spontaneously by age 5); Grade IV–V — endoscopic subureteral injection (STING/DEFLUX) or open/laparoscopic ureteral reimplantation.', steps:[], tags:[{cls:'ct-teal',text:'Grade I–V'},{cls:'ct-red',text:'Reflux Nephropathy'},{cls:'ct-amber',text:'STING Injection'},{cls:'ct-navy',text:'Reimplantation'}] },
          { id:'c14', num:'14', title:'Renal Papilla & Papillary Necrosis — Causes, Staging & Imaging', webp:'../images/renal-papilla-papillary-necrosis-hybrid.webp', png:'../images/renal-papilla-papillary-necrosis-hybrid.png', alt:'Renal papilla and papillary necrosis hybrid diagram — NSAID sickle cell analgesic nephropathy ischemia mechanism', accent:'navy',  render:'Hybrid', desc:'Normal renal papilla anatomy: the papilla projects into a minor calyx; straight collecting ducts (of Bellini) open at the area cribrosa; vasa recta supply the papilla in a countercurrent arrangement — making the papillary tip the most hypoxic and ischemia-vulnerable zone. Papillary necrosis (RPN) causes mnemonic POSTCARDS: Phenacetin/analgesic nephropathy, Obstruction, Sickle cell disease/trait, Tuberculosis, Cirrhosis/alcoholism, Acute pyelonephritis, Renal vein thrombosis, Diabetes mellitus, Systemic vasculitis. Stages: early (medullary necrosis, no detachment) → papillary form (partial) → calyceal sloughing (ring sign on CT urogram, moth-eaten calyces). Sloughed papillae can cause ureteral colic and obstructive AKI.', steps:[], tags:[{cls:'ct-navy',text:'POSTCARDS Mnemonic'},{cls:'ct-red',text:'NSAID / Analgesic'},{cls:'ct-amber',text:'Sickle Cell Disease'},{cls:'ct-teal',text:'Ring Sign CT'}] }"""

C5_END = """          { id:'c5',  num:'05', title:'Duplex / Bifid Collecting System — Weigert-Meyer Rule', webp:'../images/duplex-collecting-system-hybrid.webp',  png:'../images/duplex-collecting-system-hybrid.png',     alt:'Duplex collecting system — hybrid diagram of bifid ureter and Weigert-Meyer rule',                   accent:'teal',  render:'Hybrid', desc:'Hybrid diagram of complete ureteral duplication: two separate renal pelves, two ureters, two ureteral orifices. Weigert-Meyer rule: the upper pole ureter inserts ectopically — inferior and medial to the normal orifice (below the trigone or even into vagina/urethra in females) and is prone to obstruction and ureterocele; the lower pole ureter inserts normally but is prone to VUR due to a short intramural tunnel.', steps:[], tags:[] },"""

html = html.replace(C5_END, C5_END + NEW_COND_S1 + ",", 1)

# Add new conditions section for UTI anatomy
NEW_COND_SECTION = """      },
      {
        title: 'Infection & urologic pathology', badge: 'UTI · Obstruction', badgeClass: 'badge-green',
        items: [
          { id:'c15', num:'15', title:'UTI Pathogenesis — Urethral Anatomy & Sex-Based Risk',  webp:'../images/uti-urethra-sex-comparison-hybrid.webp',             png:'../images/uti-urethra-sex-comparison-hybrid.png',             alt:'UTI pathogenesis urethral anatomy sex comparison — female 3-4cm male 18-22cm ascending infection hybrid diagram', accent:'green', render:'Hybrid', desc:'Hybrid panel explaining anatomical basis of sex disparity in UTI rates: Female urethra 3–4 cm vs male 18–22 cm — periurethral colonization (E. coli, Staphylococcus saprophyticus) reaches the bladder more easily. Female anatomical risk factors: proximity of external meatus to vaginal introitus and anus, absence of prostatic antibacterial zinc secretion, hormonal effects on urothelial defense. Ascending infection pathway: periurethral colonization → urethra → bladder (uncomplicated cystitis) → VUR or instrumentation → ureter → renal pelvis (pyelonephritis) → bacteremia (urosepsis). CKD-specific risks: impaired neutrophil function, glucosuria (diabetic CKD), instrumented access, immunosuppression (transplant). Risk stratification: uncomplicated vs complicated (structural abnormality, CKD, catheter, immunocompromised).', steps:[], tags:[{cls:'ct-green',text:'Ascending Infection'},{cls:'ct-teal',text:'Urethral Length'},{cls:'ct-red',text:'Urosepsis Risk'},{cls:'ct-amber',text:'CKD Vulnerability'}] },
        ]"""

OLD_COND_S2_START = """      {
        title: 'Vascular & neoplastic', badge: 'Acquired', badgeClass: 'badge-red',"""

html = html.replace(OLD_COND_S2_START, NEW_COND_SECTION + """
      },
      {
        title: 'Vascular & neoplastic', badge: 'Acquired', badgeClass: 'badge-red',""", 1)

# ── NEW PROCEDURE ITEMS ───────────────────────────────────────────────────────
# Add p19 to biopsy/urologic section (after p18)
NEW_PROC_S1 = """,
          { id:'p19', num:'P19', title:'Percutaneous Nephrostomy — Anatomy, Access Zones & PCNL', webp:'../images/percutaneous-nephrostomy-anatomy-hybrid.webp', png:'../images/percutaneous-nephrostomy-anatomy-hybrid.png', alt:'Percutaneous nephrostomy anatomy — Brodels avascular plane lower pole posterior calyx access zones PCNL hybrid diagram', accent:'teal', render:'Hybrid', desc:'Hybrid anatomical diagram of percutaneous nephrostomy (PCN) access zones: optimal entry via posterior lower-pole calyx through Brödel\'s avascular plane (lateral to arcuate vessels, between anterior and posterior segmental arteries) minimizes hemorrhage risk. Patient positioned prone or prone-oblique; puncture angle 30° from vertical avoids pleural transgression. Anatomic danger zones: above 12th rib → pleural violation (pneumothorax, hydrothorax); retrorenal colon (1% population, especially left side — CT-confirmed before supra-costal access). Three PCN configurations: (1) Simple 8–10F pigtail drainage; (2) Balloon-retained Malecot; (3) Large-bore 24–30F access sheath for percutaneous nephrolithotomy (PCNL) — stone clearance.', steps:['Scout CT/fluoroscopy confirms calyceal anatomy; prone positioning','22G Chiba needle enters posterior lower calyx; aspiration confirms position','Seldinger: J-wire → fascial dilation → pigtail or large-bore sheath placed','PCNL: nephroscope passed through sheath; ultrasonic/laser lithotripsy of stone'], tags:[{cls:'ct-teal',text:"Brödel's Plane"},{cls:'ct-amber',text:'Lower Pole Access'},{cls:'ct-red',text:'Pleural Risk'},{cls:'ct-navy',text:'PCNL Access'}] }"""

P18_END = """          { id:'p18', num:'P18', title:'Robotic Radical Prostatectomy (RARP) — Da Vinci Technique', webp:'../images/robotic-radical-prostatectomy-hybrid-v2.webp', png:'../images/robotic-radical-prostatectomy-hybrid-v2.png', alt:'Robotic radical prostatectomy Da Vinci technique', accent:'teal', render:'Hybrid', desc:'Transperitoneal 6-port Da Vinci robot: camera port periumbilical, 2 robotic arms, 1–2 assistant ports. Retzius space developed, bladder dropped. Endopelvic fascia incised, puboprostatic ligaments divided. Nerve-sparing: NVBs dissected posterolateral to prostate using athermal technique (cold scissors, clips — no monopolar energy near nerves). Bladder neck dissection, seminal vesicle excision, vas deferens division. Prostate specimen in bag. Running 3-0 Monocryl urethrovesical anastomosis (Van Velthoven technique). Extended pelvic lymph node dissection for intermediate/high risk. Catheter 7–10 days.', steps:['6-port transperitoneal; bladder dropped, endopelvic fascia incised','Nerve-sparing: NVB preserved posterolateral; athermal dissection','Seminal vesicles + vas deferens divided; prostate pedicles clipped','Urethrovesical anastomosis running suture; catheter 7–10 days; EPLND if indicated'], tags:[{cls:'ct-teal',text:'Nerve-Sparing NVB'},{cls:'ct-amber',text:'Da Vinci Robotic'},{cls:'ct-navy',text:'ED / Incontinence'},{cls:'ct-green',text:'RARP'}] },"""

html = html.replace(P18_END, P18_END + NEW_PROC_S1 + ",", 1)

# Add p20 to PD section (after p14)
NEW_PROC_PD = """,
          { id:'p20', num:'P20', title:'Peritoneal Membrane — Layers, Transport & Three-Pore Model', webp:'../images/peritoneal-membrane-layers-hybrid.webp', png:'../images/peritoneal-membrane-layers-hybrid.png', alt:'Peritoneal membrane layers three-pore model transport — mesothelial cells aquaporin-1 small large pores hybrid diagram', accent:'amber', render:'Hybrid', desc:'Hybrid cross-section of the peritoneal membrane from dialysate to capillary: (1) Dialysate fluid film → (2) Mesothelium (single layer of mesothelial cells with glycocalyx, surface area 1–2 m²) → (3) Interstitium (extracellular matrix, lymphatics) → (4) Capillary endothelium. Three-pore transport model: ultra-small pores (aquaporin-1 water channels — responsible for free water transport, inhibited by caffeine) → small pores (4–5 nm radius — pass urea, creatinine, electrolytes; most solute clearance occurs here) → large pores (20–40 nm — albumin and macromolecules). Glucose osmotic gradient drives ultrafiltration; icodextrin (colloid) provides sustained UF in high transporters. PET (peritoneal equilibration test) classifies transporters: high (fast diffusion, poor UF) → short dwells/APD; low (slow diffusion, good UF) → long dwells/CAPD.', steps:['Dialysate glucose gradient drives osmotic UF across mesothelium','AQP-1 (aquaporin-1) channels — free water transport, ~40% of UF','Small pores: urea, creatinine, Na transport by diffusion/convection','PET D/P creatinine at 4h: >0.65 = high transporter → APD; <0.5 = low → CAPD'], tags:[{cls:'ct-amber',text:'Three-Pore Model'},{cls:'ct-teal',text:'Aquaporin-1'},{cls:'ct-green',text:'PET Classification'},{cls:'ct-navy',text:'Osmotic UF'}] }"""

P14_END = """          { id:'p14', num:'P14', title:'Therapeutic Plasma Exchange — Centrifugal & Membrane TPE', webp:'../images/plasmapheresis-therapeutic-hybrid-v2.webp', png:'../images/plasmapheresis-therapeutic-hybrid-v2.png', alt:'Therapeutic plasma exchange — centrifugal vs membrane separation', accent:'amber', render:'Hybrid', desc:'Centrifugal TPE: whole blood spun in centrifuge bowl — plasma (low density) rises to top, cells to bottom; plasma removed and replaced. Membrane TPE: plasma separated across 0.2–0.6 μm pores (sieving coefficient ≈1 for all proteins). One plasma volume (40–60 mL/kg) exchanged per session removes ~63% of pathogenic antibody. Replacement: 5% albumin prevents coagulopathy risk of FFP (preferred for most conditions); FFP mandatory for TTP (replaces ADAMTS13). Complications: hypocalcemia (citrate), hypovolemia, allergic reactions (FFP), bleeding (if albumin replacement depletes clotting factors).', steps:['Central or large peripheral access; anticoagulation with citrate or heparin','1.0–1.5× plasma volume exchanged per session (40–60 mL/kg)','Replacement: albumin 5% (most) or FFP (TTP — replaces ADAMTS13)','Monitor: hypocalcemia (citrate), allergic reactions (FFP), hypotension'], tags:[{cls:'ct-amber',text:'ASFA Category I'},{cls:'ct-teal',text:'TTP / Anti-GBM'},{cls:'ct-red',text:'FSGS Recurrence'},{cls:'ct-navy',text:'ADAMTS13'}] },"""

html = html.replace(P14_END, P14_END + NEW_PROC_PD + ",", 1)

# Add p21, p22 to HD access section (after p12)
NEW_PROC_HD = """,
          { id:'p21', num:'P21', title:'Forearm AVF — Balloon Angioplasty (PTA) for Stenosis',  webp:'../images/forearm-avf-ballon-angioplasty.webp',             png:'../images/forearm-avf-ballon-angioplasty.png',             alt:'Forearm AVF balloon angioplasty PTA for stenosis — retrograde access juxta-anastomotic cephalic vein fluoroscopy', accent:'green', render:'Hybrid', desc:'Percutaneous transluminal angioplasty (PTA) of a stenotic forearm radiocephalic AVF. Stenosis sites: juxta-anastomotic (most common — within 2 cm of anastomosis, caused by turbulent flow-induced intimal hyperplasia), mid-vein, cephalic arch (brachiocephalic AVF). Technique: retrograde venipuncture of the outflow vein → heparinization → guidewire crosses stenosis under fluoroscopy → 5–7 mm non-compliant or cutting balloon inflated for 60–120s → post-PTA fistulogram confirms <30% residual stenosis. Cutting balloon (microsurgical blades) for resistant fibrotic stenosis. Drug-coated balloons (paclitaxel) reduce restenosis rates. Stent placement reserved for elastic recoil or rupture. Primary PTA success >90%; 1-year primary patency ~40–50%.', steps:['Access AVF retrograde; heparin 2000–3000 U IV before wire passage','Fluoroscopy confirms stenosis location and degree (fistulogram)','Non-compliant or cutting balloon: 5–7mm, 60–120s inflation × 2–3 passes','Post-PTA fistulogram: residual stenosis <30%; flow rates confirm adequacy'], tags:[{cls:'ct-green',text:'PTA Angioplasty'},{cls:'ct-teal',text:'Juxta-anastomotic'},{cls:'ct-amber',text:'Cutting Balloon'},{cls:'ct-red',text:'Intimal Hyperplasia'}] },
          { id:'p22', num:'P22', title:'AVF / AVG Pseudoaneurysm — Recognition, Risk & Repair',  webp:'../images/pseudoaneurysm-anatomy-patient-education-hybrid.webp', png:'../images/pseudoaneurysm-anatomy-patient-education-hybrid.png', alt:'AVF AVG pseudoaneurysm anatomy patient education — rupture risk yin-yang flow covered stent aneurysmorrhaphy hybrid', accent:'green', render:'Hybrid', desc:'Hybrid patient education + anatomical panel: True aneurysm — all three vessel wall layers (intima/media/adventitia) are intact but thinned and dilated from repetitive needling at the same site (rope-ladder technique protects against this). Pseudoaneurysm — contained peri-vascular hematoma communicating with the vessel lumen through a defect in the wall; typically post-puncture or post-dehiscence. US differentiation: true aneurysm shows laminar turbulent flow; pseudoaneurysm shows classic "yin-yang" swirling color Doppler pattern and "to-and-fro" spectral waveform at the neck. High-risk features requiring urgent referral (within 24–48h): skin thinning/discoloration over aneurysm, ulceration or scab, rapid expansion (>5 mm/month), diameter >3 cm, infection signs. Management: endovascular (covered stent graft); surgical (aneurysmorrhaphy with patch, segmental resection with PTFE interposition, or ligation with new access creation).', steps:['US Doppler: yin-yang sign (pseudo) vs turbulent laminar flow (true aneurysm)','High-risk features: skin thinning, ulceration, rapid growth, infection → urgent referral','Endovascular: covered stent maintains access patency','Surgical: aneurysmorrhaphy or segmental resection; buttonhole cannulation avoided'], tags:[{cls:'ct-red',text:'Rupture Risk'},{cls:'ct-teal',text:'Yin-Yang US Sign'},{cls:'ct-amber',text:'Covered Stent'},{cls:'ct-navy',text:'Aneurysmorrhaphy'}] }"""

P12_END = """          { id:'p12', num:'P12', title:'Fistulogram & Percutaneous Declotting — AV Access Salvage', webp:'../images/fistulogram-declotting-hybrid-v2.webp', png:'../images/fistulogram-declotting-hybrid-v2.png', alt:'Fistulogram and percutaneous AV access declotting — contrast venogram, balloon angioplasty and pharmacomechanical thrombolysis', accent:'green', render:'Hybrid', desc:'Fistulogram via retrograde venipuncture: contrast injection maps stenosis location, degree, and thrombus extent. PTA with 6–8 mm balloon (non-compliant) targets venous anastomotic stenosis — residual stenosis <30% is the technical success criterion. For thrombosed access: pharmacomechanical thrombolysis with tPA infusion + Arrow-Trerotola or Helix Clot Buster device, followed by underlying stenosis angioplasty. Technical success 85–90%; primary patency 50% at 6 months post-PTA. Surgical revision for recurrent early failures.', steps:['Retrograde venipuncture; contrast injection maps stenosis + thrombus','Crossing wire through stenosis / thrombus under fluoroscopy','Balloon PTA at stenotic segment; residual stenosis <30% target','Thrombus: tPA infusion + mechanical maceration; confirm flow with fistulogram'], tags:[{cls:'ct-green',text:'PTA Angioplasty'},{cls:'ct-teal',text:'Retrograde Access'},{cls:'ct-red',text:'Venous Stenosis'},{cls:'ct-amber',text:'tPA Thrombolysis'}] },"""

html = html.replace(P12_END, P12_END + NEW_PROC_HD + ",", 1)

# ── UPDATE STAT PILLS ─────────────────────────────────────────────────────────
html = html.replace(
    '<div class="stat-num">10</div><div class="stat-label">Structure</div>',
    '<div class="stat-num">19</div><div class="stat-label">Structure</div>'
)
html = html.replace(
    '<div class="stat-num">14</div><div class="stat-label">Pathology</div>',
    '<div class="stat-num">17</div><div class="stat-label">Pathology</div>'
)
html = html.replace(
    '<div class="stat-num">18</div><div class="stat-label">Interventions</div>',
    '<div class="stat-num">22</div><div class="stat-label">Interventions</div>'
)

# ── UPDATE TAB COUNTS ─────────────────────────────────────────────────────────
html = html.replace(
    'Anatomy <span class="tab-count">10</span>',
    'Anatomy <span class="tab-count">19</span>'
)
html = html.replace(
    'Medical Conditions <span class="tab-count">14</span>',
    'Medical Conditions <span class="tab-count">17</span>'
)
html = html.replace(
    'Procedures <span class="tab-count">18</span>',
    'Procedures <span class="tab-count">22</span>'
)

GUIDE.write_text(html, encoding='utf-8')

# Verify
import re
ids = re.findall(r"id:'([apcesA-Z0-9]+)'", html)
print(f"Total card IDs found : {len(ids)}")
print(f"Anatomy  : {sum(1 for i in ids if i.startswith('a'))}")
print(f"Conditions: {sum(1 for i in ids if i.startswith('c'))}")
print(f"Procedures: {sum(1 for i in ids if i.startswith('p'))}")
print(f"Embryology: {sum(1 for i in ids if i.startswith('e'))}")
print(f"File size : {len(html)//1024} KB")
