#!/usr/bin/env python3
"""
patch_references_accordion.py — williamriveromd.com

Gives every guide a collapsible (accordion) **References** section placed
immediately before the signature block (.dr-card-wrap), so citations live in the
body of the page rather than only in the print footer.

Citations are sourced, in order, from:
  1. The footer references line:  <p>References: A · B · C</p>
     (also handles <p><strong>References</strong></p><p>A · B</p>).
  2. The hero-meta "Guidelines:" value, when there is no footer references line.
Citations are split on the middot separator (· / &middot;).

The accordion uses inline styles (with the guide's own CSS custom properties) so
that patch_master_css.py never clobbers it. Markers REFERENCES-ACC-START/END
make the block idempotent — re-running refreshes it in place.

Guides with NO sourceable citations are NOT given a fabricated reference list;
they are reported so a human can add real references. (Medical citations must be
real.) Pure printable log/blank sheets are skipped.

Usage:
    python3 patch_references_accordion.py
    python3 patch_references_accordion.py --dry-run
    python3 patch_references_accordion.py --guide understanding-ckd.html
    python3 patch_references_accordion.py --report   # just list reference coverage
"""

import re
import json
import argparse
from pathlib import Path

START = "<!-- REFERENCES-ACC-START -->"
END = "<!-- REFERENCES-ACC-END -->"

SKIP_EXACT = {"index.html"}
# Printable sheets / pure tools — not narrative guides; no references expected.
SKIP_SUFFIX = ("-log.html", "-log-blank.html", "-blank.html")

LABELS = (
    '<span data-lang="en">References</span>'
    '<span class="lang-hidden" data-lang="tl">Mga Sanggunian</span>'
    '<span class="lang-hidden" data-lang="ceb">Mga Tinubdan</span>'
    '<span class="lang-hidden" data-lang="kap">Reng Reperensya</span>'
)


def find_project_dir(script_path: Path) -> Path:
    for candidate in [script_path.parent, script_path.parent.parent]:
        if (candidate / "guides").is_dir() and (candidate / "index.html").exists():
            return candidate
    raise FileNotFoundError("Cannot find project root. Run from the repo directory.")


def extract_citations(text: str):
    """Return a list of citation strings sourced from footer refs or hero-meta."""
    raw = ""
    # Footer: <p>References: ...</p>  OR  <p><strong>References</strong></p><p>...</p>
    m = re.search(r'<p>\s*References\s*:?\s*(.*?)</p>', text, re.S | re.I)
    if m and m.group(1).strip():
        raw = m.group(1)
    else:
        m = re.search(
            r'<p>\s*<strong>\s*References\s*</strong>\s*</p>\s*<p>(.*?)</p>',
            text, re.S | re.I,
        )
        if m:
            raw = m.group(1)
    if not raw:
        # Fallback: hero-meta "Guidelines:" value.
        m = re.search(r'<strong>\s*Guidelines\s*:?\s*</strong>\s*(.*?)</span>', text, re.S | re.I)
        if m:
            raw = m.group(1)
    if not raw:
        return []

    # Strip any inline tags EXCEPT a small whitelist used by APA-formatted
    # citations: <em>/<i> for italicised journal+volume, <strong>/<b> for
    # emphasis, and <a …> for DOI/URL links. Everything else (stray spans,
    # data-lang attrs, font tags from legacy footers) is stripped.
    raw = re.sub(
        r'<(?!/?(?:em|i|strong|b|a)(?:\s|>|/))[^>]+>', '', raw, flags=re.I
    )
    parts = re.split(r'\s*(?:&middot;|·|&#183;)\s*', raw)
    cites = [re.sub(r'\s+', ' ', p).strip() for p in parts]
    cites = [c for c in cites if c and c.lower() not in ("references", "guidelines")]
    return cites


def build_block(cites) -> str:
    items = "\n".join(f'<li>{c}</li>' for c in cites)
    n = len(cites)
    return (
        f"{START}\n"
        '<!-- Accordion references — generated by patch_references_accordion.py. '
        'Inline styles so patch_master_css.py will not clobber it. -->\n'
        '<section class="ref-section" style="max-width:860px;margin:8px auto 0;padding:0 32px;">\n'
        '<details class="ref-acc" style="border:1px solid var(--border);border-radius:12px;'
        'background:var(--white);overflow:hidden;">\n'
        '<summary style="cursor:pointer;list-style:none;padding:15px 20px;'
        'font-family:Inter,system-ui,sans-serif;font-weight:600;font-size:15px;'
        'color:var(--text);display:flex;align-items:center;gap:10px;">\n'
        '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
        'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
        'style="flex:none;color:var(--teal);"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/>'
        '<path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>\n'
        f'{LABELS}\n'
        f'<span style="margin-left:auto;font-weight:500;font-size:12px;color:var(--text-muted);">{n} source{"s" if n != 1 else ""}</span>\n'
        '</summary>\n'
        '<ol style="margin:0;padding:4px 26px 18px 44px;font-size:13.5px;'
        'line-height:1.75;color:var(--text-mid);">\n'
        f'{items}\n'
        '</ol>\n'
        '</details>\n'
        '</section>\n'
        f"{END}"
    )


def patch_guide(path: Path, dry_run: bool, overrides: dict) -> str:
    text = path.read_text(encoding="utf-8")
    original = text

    if 'class="dr-card-wrap"' not in text:
        return "skip (no signature block)"

    cites = extract_citations(text)
    if not cites:
        # Citations supplied externally (e.g. compiled from the guide's own
        # inline-cited sources) for guides without a footer references line.
        cites = [c.strip() for c in overrides.get(path.name, []) if c.strip()]
    if not cites:
        return "NO REFS (needs real citations)"

    block = build_block(cites)

    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text,
                      count=1, flags=re.S)
    else:
        # Insert before the DR CARD comment if present, else before .dr-card-wrap.
        anchor = re.search(r'(\n)(?:<!-- DR CARD -->\s*)*<div class="dr-card-wrap">', text)
        if not anchor:
            anchor = re.search(r'(\n)<div class="dr-card-wrap">', text)
        if not anchor:
            return "skip (cannot locate signature anchor)"
        insert_at = anchor.start()
        text = text[:insert_at] + "\n" + block + text[insert_at:]

    if text == original:
        return "unchanged"
    if not dry_run:
        path.write_text(text, encoding="utf-8")
    return f"✓ {len(cites)} source(s)"


def main():
    ap = argparse.ArgumentParser(description="Add accordion References to guides.")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--guide", help="patch a single guide (filename in guides/)")
    ap.add_argument("--report", action="store_true", help="list coverage only")
    ap.add_argument("--overrides", help="JSON file: {filename: [citations]} for "
                    "guides lacking a footer references line")
    args = ap.parse_args()

    overrides = {}
    if args.overrides:
        overrides = json.loads(Path(args.overrides).read_text(encoding="utf-8"))

    project_dir = find_project_dir(Path(__file__).resolve())
    guides_dir = project_dir / "guides"

    def eligible(p):
        if p.name in SKIP_EXACT:
            return False
        if p.name.endswith(SKIP_SUFFIX):
            return False
        return True

    targets = ([guides_dir / args.guide] if args.guide
               else sorted(p for p in guides_dir.glob("*.html") if eligible(p)))

    changed, missing = 0, []
    for path in targets:
        if not path.exists():
            print(f"  ! {path.name}: not found"); continue
        if not eligible(path):
            continue
        if args.report:
            cites = extract_citations(path.read_text(encoding="utf-8"))
            tag = f"{len(cites)} src" if cites else "—— none"
            print(f"  {tag:>8}  {path.name}")
            if not cites:
                missing.append(path.name)
            continue
        status = patch_guide(path, args.dry_run, overrides)
        if status.startswith("✓"):
            changed += 1
        elif status.startswith("NO REFS"):
            missing.append(path.name)
        if not status.startswith("unchanged") and not status.startswith("skip"):
            print(f"  {status}  {path.name}")

    if not args.report:
        verb = "Would update" if args.dry_run else "Updated"
        print(f"\n{verb} {changed} guide(s).")
    if missing:
        print(f"\n{len(missing)} guide(s) need real references added (no citations to source):")
        for name in missing:
            print(f"  - {name}")


if __name__ == "__main__":
    main()
